---
# This template configures each role to use Vlans on a single nic for
# each isolated network, but uses multiple nic's on each node:
#
# nic1 = pxe/management/ctlplane
# nic2 = VLAN trunk for network isolation
# nic3 = public/external access
#
# This template assumes use of network-isolation.yaml.
#
# FIXME: if/when we add functionality to heatclient to include heat
# environment files we should think about using it here to automatically
# include network-isolation.yaml.
resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: vlans//compute.yaml

  OS::TripleO::Controller::Net::SoftwareConfig: vlans//controller.yaml

  OS::TripleO::CephStorage::Net::SoftwareConfig: vlans//ceph-storage.yaml

parameter_defaults:
 
    ExternalNetCidr: 172.18.0.0/16
    ExternalAllocationPools: [{'start': '172.18.0.50', 'end': '172.18.0.150' }]
    ExternalInterfaceDefaultRoute: 172.18.0.1
    ExternalNetworkVlanID: 300
    InternalApiNetCidr: 172.17.1.0/24
    InternalApiAllocationPools: [{'start': '172.17.1.10', 'end': '172.17.1.149' }]
    InternalApiNetworkVlanID: 301
    StorageNetCidr: 172.17.3.0/24
    StorageAllocationPools: [{'start': '172.17.3.10', 'end': '172.17.3.149' }]
    StorageNetworkVlanID: 302
    StorageMgmtNetCidr: 172.17.4.0/24
    StorageMgmtAllocationPools: [{'start': '172.17.4.10', 'end': '172.17.4.149' }]
    StorageMgmtNetworkVlanID: 303
    TenantNetCidr: 172.17.2.0/24
    TenantAllocationPools: [{'start': '172.17.2.10', 'end': '172.17.2.150'}]
    TenantNetworkVlanID: 304

    DnsServers: ['192.168.24.1']
    EC2MetadataIp: 192.168.24.1
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: "24"
