- name: ControllerStorageNfs
  count: 3
  hostname_format: controller-%index%
  defaults:
    profile: controller
    network_config:
      default_route_network:
      - External
      template: /home/stack/virt/network/vlans/controller.j2
    networks:
    - network: ctlplane
      vif: true
    - network: storage
    - network: storage_mgmt
    - network: storage_nfs
    - network: internal_api
    - network: tenant
    - network: external
- name: Compute
  count: 9
  hostname_format: compute-%index%
  defaults:
    profile: compute
    network_config:
      template: /home/stack/virt/network/vlans/compute.j2
    networks:
    - network: ctlplane
      vif: true
    - network: storage
    - network: internal_api
    - network: tenant
- name: CephStorage
  count: 3
  hostname_format: ceph-%index%
  defaults:
    profile: ceph
    network_config:
      template: /home/stack/virt/network/vlans/ceph-storage.j2
    networks:
    - network: ctlplane
      vif: true
    - network: storage
    - network: storage_mgmt
