parameter_defaults:
    CephStorageNetworkConfigTemplate: /home/stack/virt/network/vlans/ceph-storage.j2
    ComputeNetworkConfigTemplate: /home/stack/virt/network/vlans/compute.j2
    ComputeParameters:
        NeutronBridgeMappings: ''
    ControllerNfsNetworkConfigTemplate: /home/stack/virt/network/vlans/controller.j2
    ControllerNfsParameters:
        NeutronBridgeMappings: datacentre:br-ex,tenant:br-isolated
    NeutronEnableDVR: 'false'
    NeutronExternalNetworkBridge: ''
    NeutronNetworkType: geneve,vlan
    NeutronNetworkVLANRanges: datacentre:2001:4000,tenant:1000:2000
    NeutronTunnelTypes: geneve
resource_registry:
    OS::TripleO::CephStorage::Net::SoftwareConfig: OS::Heat::None
    OS::TripleO::Compute::Net::SoftwareConfig: OS::Heat::None
    OS::TripleO::Controller::Net::SoftwareConfig: OS::Heat::None
